version: "3.7"

services:
  php:
    build:
      context: .
    volumes:
      - ".:/app"
      - "~/.ssh:/root/.ssh"
      #- '$SSH_AUTH_SOCK:/ssh-agent'
    environment:
      SSH_AUTH_SOCK: "/ssh-agent"
      APP_NAME: "Qubet"
      APP_ENV: "test"
      APP_KEY: "base64:e2kUcSg09u0MT7bWMOW9ozEd16JpbSYrCHxyLX2jAhU="
      APP_DEBUG: "true"
      APP_URL: "/"
      APP_TIMEZONE: "UTC"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_DATABASE: "qubet"
      DB_USERNAME: "qubet"
      DB_PASSWORD: "qubet"
    expose:
      - 9000
    depends_on:
      - db

  nginx:
    build:
      context: "./docker/nginx"
    ports:
      - "80:80"
    environment:
      NGINX_PHP_UPSTREAM: php
      # Start URI with /template/...
      NGINX_URI_PREFIX: /
    volumes:
      - "./var/log/nginx:/var/log/nginx"
    depends_on:
      - php

  db:
    build:
      context: ./docker/mysql
    ports:
      - "33061:3306"
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      DB_HOST: db
      DB_DATABASE: "qubet"
      DB_USERNAME: "qubet"
      DB_PASSWORD: "qubet"
      MYSQL_AUTH_COMMAND: --default-authentication-plugin=mysql_native_password

  elk:
    image: "willdurand/elk"
    ports:
      - "900:80"
    volumes:
      - "./docker/logstash:/etc/logstash"
      - "./docker/logstash/patterns:/opt/logstash/patterns"
      - "./var/log/laravel:/var/log/laravel"
      - "./var/log/nginx:/var/log/nginx"

volumes:
  db_volume:
